# Generated by Django 4.2.26 on 2026-04-25 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='detections/%Y/%m/%d/', verbose_name='আপলোড করা ছবি')),
                ('confidence', models.FloatField(default=0.0, verbose_name='আত্মবিশ্বাস স্কোর')),
                ('status', models.CharField(choices=[('pending', 'অপেক্ষমান'), ('completed', 'সম্পন্ন'), ('failed', 'ব্যর্থ')], db_index=True, default='pending', max_length=20, verbose_name='অবস্থা')),
                ('result_data', models.JSONField(blank=True, default=dict, verbose_name='ফলাফল ডেটা')),
                ('is_bookmarked', models.BooleanField(default=False, verbose_name='বুকমার্ক')),
                ('notes', models.TextField(blank=True, verbose_name='নোট')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'শনাক্তকরণ',
                'verbose_name_plural': 'শনাক্তকরণসমূহ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bn', models.CharField(max_length=200, verbose_name='রোগের নাম (বাংলা)')),
                ('name_en', models.CharField(max_length=200, verbose_name='রোগের নাম (ইংরেজি)')),
                ('description_bn', models.TextField(blank=True, verbose_name='বিবরণ (বাংলা)')),
                ('crop_type', models.CharField(db_index=True, max_length=100, verbose_name='ফসলের ধরণ')),
                ('severity', models.CharField(choices=[('low', 'কম'), ('medium', 'মাঝারি'), ('high', 'উচ্চ'), ('critical', 'জরুরি')], default='medium', max_length=20, verbose_name='তীব্রতা')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'রোগ',
                'verbose_name_plural': 'রোগসমূহ',
                'ordering': ['name_bn'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_bn', models.TextField(verbose_name='চিকিৎসা (বাংলা)')),
                ('pesticide_bn', models.TextField(blank=True, verbose_name='কীটনাশক (বাংলা)')),
                ('prevention_bn', models.TextField(blank=True, verbose_name='প্রতিরোধ (বাংলা)')),
                ('dosage', models.CharField(blank=True, max_length=200, verbose_name='মাত্রা')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='detection.disease', verbose_name='রোগ')),
            ],
            options={
                'verbose_name': 'পরামর্শ',
                'verbose_name_plural': 'পরামর্শসমূহ',
            },
        ),
        migrations.CreateModel(
            name='DiseaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='disease_references/', verbose_name='ছবি')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='ক্যাপশন')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='detection.disease', verbose_name='রোগ')),
            ],
            options={
                'verbose_name': 'রোগের ছবি',
                'verbose_name_plural': 'রোগের ছবিসমূহ',
            },
        ),
        migrations.AddIndex(
            model_name='disease',
            index=models.Index(fields=['name_en'], name='idx_disease_name_en'),
        ),
        migrations.AddIndex(
            model_name='disease',
            index=models.Index(fields=['crop_type'], name='idx_disease_crop'),
        ),
        migrations.AddField(
            model_name='detection',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='detection.disease', verbose_name='শনাক্তকৃত রোগ'),
        ),
        migrations.AddField(
            model_name='detection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to=settings.AUTH_USER_MODEL, verbose_name='ব্যবহারকারী'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['user', '-created_at'], name='idx_detection_user_date'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['status'], name='idx_detection_status'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['is_bookmarked'], name='idx_detection_bookmark'),
        ),
    ]
