# Generated by Django 4.2.26 on 2026-04-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseaseimage',
            name='is_gallery',
            field=models.BooleanField(default=False, help_text='Is this a morphologically similar disease image for the gallery?', verbose_name='গ্যালারি ছবি'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='pesticide_cost_bn',
            field=models.CharField(blank=True, max_length=100, verbose_name='কীটনাশকের মূল্য (বাংলা)'),
        ),
    ]
