# Generated by Django 4.2.26 on 2026-04-25 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('detection', '0002_diseaseimage_is_gallery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='বার্তা')),
                ('is_responded', models.BooleanField(default=False, verbose_name='উত্তর দেওয়া হয়েছে')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_requests', to='detection.disease', verbose_name='রোগ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_requests', to=settings.AUTH_USER_MODEL, verbose_name='ব্যবহারকারী')),
            ],
            options={
                'verbose_name': 'তথ্যের অনুরোধ',
                'verbose_name_plural': 'তথ্যের অনুরোধসমূহ',
                'ordering': ['-created_at'],
            },
        ),
    ]
