# Generated by Django 4.2.26 on 2026-04-25 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='voice_messages/%Y/%m/%d/', verbose_name='অডিও ফাইল')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='সময়কাল (সেকেন্ড)')),
                ('is_read', models.BooleanField(default=False, verbose_name='শোনা হয়েছে')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_voice_messages', to=settings.AUTH_USER_MODEL, verbose_name='প্রাপক')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_voice_messages', to=settings.AUTH_USER_MODEL, verbose_name='প্রেরক')),
            ],
            options={
                'verbose_name': 'ভয়েস বার্তা',
                'verbose_name_plural': 'ভয়েস বার্তাসমূহ',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['sender', 'receiver'], name='idx_voice_sender_receiver')],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='বার্তা')),
                ('is_read', models.BooleanField(default=False, verbose_name='পঠিত')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='প্রাপক')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='প্রেরক')),
            ],
            options={
                'verbose_name': 'চ্যাট বার্তা',
                'verbose_name_plural': 'চ্যাট বার্তাসমূহ',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['sender', 'receiver'], name='idx_chat_sender_receiver'), models.Index(fields=['is_read'], name='idx_chat_is_read'), models.Index(fields=['-created_at'], name='idx_chat_created')],
            },
        ),
    ]
